//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JCarrollOnlineV2.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Sql {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Sql() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JCarrollOnlineV2.Properties.Sql", typeof(Sql).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DROP PROCEDURE dbo.NLog_AddEntry.
        /// </summary>
        internal static string dbo_DropWriteLog {
            get {
                return ResourceManager.GetString("dbo_DropWriteLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE PROCEDURE [dbo].[NLog_AddEntry]
        ///(
        ///  @machineName nvarchar(200),
        ///  @siteName nvarchar(200),
        ///  @logged datetime,
        ///  @level varchar(5),
        ///  @userName nvarchar(200),
        ///  @message nvarchar(max),
        ///  @logger nvarchar(300),
        ///  @properties nvarchar(max),
        ///  @serverName nvarchar(200),
        ///  @port nvarchar(100),
        ///  @url nvarchar(2000),
        ///  @https bit,
        ///  @serverAddress nvarchar(100),
        ///  @remoteAddress nvarchar(100),
        ///  @callSite nvarchar(300),
        ///  @exception nvarchar(max)
        ///) AS
        ///BEGIN TRANSACTION
        ///  INSERT INTO [d [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string dbo_WriteLog {
            get {
                return ResourceManager.GetString("dbo_WriteLog", resourceCulture);
            }
        }
    }
}
