//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JCarrollOnlineV2.WCFClient.JCarrollOnlineV2Service {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="JCarrollOnlineV2Service.IJCarrollOnlineV2Service")]
    public interface IJCarrollOnlineV2Service {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJCarrollOnlineV2Service/Login", ReplyAction="http://tempuri.org/IJCarrollOnlineV2Service/LoginResponse")]
        bool Login(string userName, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IJCarrollOnlineV2Service/Login", ReplyAction="http://tempuri.org/IJCarrollOnlineV2Service/LoginResponse")]
        System.Threading.Tasks.Task<bool> LoginAsync(string userName, string password);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IJCarrollOnlineV2ServiceChannel : global::JCarrollOnlineV2.WCFClient.JCarrollOnlineV2Service.IJCarrollOnlineV2Service, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class JCarrollOnlineV2ServiceClient : System.ServiceModel.ClientBase<global::JCarrollOnlineV2.WCFClient.JCarrollOnlineV2Service.IJCarrollOnlineV2Service>, global::JCarrollOnlineV2.WCFClient.JCarrollOnlineV2Service.IJCarrollOnlineV2Service {
        
        public JCarrollOnlineV2ServiceClient() {
        }
        
        public JCarrollOnlineV2ServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public JCarrollOnlineV2ServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public JCarrollOnlineV2ServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public JCarrollOnlineV2ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool Login(string userName, string password) {
            return base.Channel.Login(userName, password);
        }
        
        public System.Threading.Tasks.Task<bool> LoginAsync(string userName, string password) {
            return base.Channel.LoginAsync(userName, password);
        }
    }
}
